spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: inventory-service
              uri: lb://inventory-service
              predicates:
                - Path=/api/inventory/**
              filters:
                - TokenRelay
            - id: orders-service
              uri: lb://orders-service
              predicates:
                - Path=/api/order/**
              filters:
                - TokenRelay
            - id: products-service
              uri: lb://products-service
              predicates:
                - Path=/api/product/**
              filters:
                - TokenRelay
            - id: discovery-service
              uri: http://localhost:8761
              predicates:
                - Path=/eureka/web
              filters:
                - SetPath=/
            - id: discovery-service-static
              uri: http://localhost:8761
              predicates:
                - Path=/eureka/**
            - id: inventory-service-actuator
              uri: lb://inventory-service/actuator/inventory/**
              predicates:
                - Path=/actuator/inventory/**
              filters:
                - TokenRelay
            - id: orders-service-actuator
              uri: lb://orders-service/actuator/orders/**
              predicates:
                - Path=/actuator/orders/**
              filters:
                - TokenRelay
            - id: products-service-actuator
              uri: lb://products-service/actuator/products/**
              predicates:
                - Path=/actuator/products/**
              filters:
                - TokenRelay

  # Keycloak
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8181/realms/demo-orders-serv-realm/protocol/openid-connect/certs
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8181/realms/demo-orders-serv-realm
        registration:
          keycloak:
            provider: keycloak
            scope:
              - openid
            client-id: demo_orders_serv_client
            client-secret: KjsSWknhdPF10Aol6SgxNcVuxJI6uLY3bqQfgKZyS9XGfQcjwl2izpbVI9RwcnvqVKvFCoyCSYe5PO9S3NyC3b
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"


server:
  port: 8080

eureka:
  client:
    service-url:
      default-zone: http://eureka:password@localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

logging:
  level:
    root: info
    org.springframework.cloud.gateway: trace
#    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: info

management:
  endpoints:
    web:
      exposure:
        include:
          - health
      base-path: /actuator