spring:
  application:
    name: orders-service
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3306/ms_orders
    username: aceto82
    password: 12345678
server:
  port: 8082
