spring:
  application:
    name: orders-service
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/ms_orders
    username: aceto82
    password: 12345678
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8181/realms/demo-orders-serv-realm/protocol/openid-connect/certs
server:
  port: 0
eureka:
  client:
    service-url:
      default-zone: http://eureka:password@localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - circuitbreakers
          - circuitbreakerevents
      base-path: /actuator/orders
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
resilience4j:
  circuitbreaker:
    instances:
      orders-service:
        registerHealthIndicator: true
        sliding-window-size: 5
        sliding-window-type: count_based
        failure-rate-threshold: 50
        wait-duration-in-open-state:
          seconds: 10
        automatic-transition-from-open-to-half-open-enabled: true
        permitted-number-of-calls-in-half-open-state: 3