spring:
  application:
    name: products-service
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/ms_products
    username: aceto82
    password: 12345678
server:
  port: 8081
